Parts = {
[1] = {"TurboCharger", handling={  {"maxVelocity",0.07}, {"engineAcceleration", 0.05}  } ,type = 1  },
[2] = {"Variable Geometry Turbo", handling={  {"maxVelocity",0.1}, {"engineAcceleration", 0.07}  } ,type = 1  },
[3] = {"Twin-Turbo", handling={  {"maxVelocity",0.13}, {"engineAcceleration", 0.09}  } ,type = 1  },
[4] = {"Twin-Scroll Turbo", handling={  {"maxVelocity",0.17}, {"engineAcceleration", 0.11}  } ,type = 1  },
[5] = {"Bi-Turbo", handling={  {"maxVelocity",0.20}, {"engineAcceleration", 0.13}  } ,type = 1  },
[6] = {"Twin-Charger", handling={  {"maxVelocity",0.15}, {"engineAcceleration", 0.17}  } ,type = 1  },
[7] = {"SuperCharger", handling={  {"maxVelocity",0.07}, {"engineAcceleration", 0.10}  } ,type = 1  },
[8] = {"Intercooler", handling={  {"engineAcceleration",0.01}  } ,type = 2  },
[9] = {"Aftercooler", handling={ {"maxVelocity", 0.05}, {"engineAcceleration", 0.02} } ,type = 2  },
[10] = {"Aftercooler+Intercooler", handling={ {"maxVelocity", 0.01}, {"engineAcceleration", 0.03}  } ,type = 2 },
[11] = {"Single Point Injection", handling={ {"maxVelocity", 0.01}, {"engineAcceleration", 0.01} },type = 3  },
[12] = {"Multi Point Injection", handling={ {"maxVelocity", 0.01}, {"engineAcceleration", 0.03} },type = 3  },
[13] = {"Direct Injection", handling={ {"maxVelocity", 0.02}, {"engineAcceleration", 0.05} },type = 3  },
[14] = {"Strumienica", handling={ {"maxVelocity", 0.03}, {"engineAcceleration", 0.01} },type = 4  },
[15] = {"Tłumik przelotowy", handling={ {"maxVelocity", 0.003}, {"engineAcceleration", 0.01} },type = 5 },
[16] = {"Zwiększona średnica rur wylotowych", handling={ {"maxVelocity", 0.003}, {"engineAcceleration", 0.01} },type = 6  },
[17] = {"Sportowy kolektor wydechowy (4-2-1)", handling={ {"maxVelocity", 0.01}, {"engineAcceleration", 0.01} },type = 7  },
[18] = {"Wyścigowe kolektor wydechowy", handling={ {"maxVelocity", 0.01}, {"engineAcceleration", 0.02} },type = 7   },
[19] = {"Filtr stożkowy", handling={ {"maxVelocity", 0.005}, {"engineAcceleration", 0.005} },type = 8  },
[20] = {"Filtr gąbkowy", handling={ {"maxVelocity", 0.01}, {"engineAcceleration", 0.01} },type = 8 },
[21] = {"ECU", handling={ {"maxVelocity", 0.01}, {"engineAcceleration", 0.02} }, modifity=true, type = 9  },
[22] = {"Podstawowa modyfikacja map wtrysku", handling={ {"maxVelocity", 0.02}, {"engineAcceleration", 0.02} },type = 10 },
[23] = {"Dedykowana modiyfikacja map wtrysku", handling={ {"maxVelocity", 0.04}, {"engineAcceleration", 0.04} },type = 10 },
[24] = {"Tarcze nawiercane", handling={ {"brakeDeceleration", 0.25} },type = 11 },
[25] = {"Tarcze nacinane", handling={ {"brakeDeceleration", 0.40} },type = 11 },
[26] = {"Tarcze CFRC", handling={ {"brakeDeceleration", 0.70} },type = 11 },
[27] = {"Klocki żeliwne sportowe", handling={ {"brakeDeceleration", 0.15} },type = 12 },
[28] = {"Klocki kompozytowe", handling={ {"brakeDeceleration", 0.30 } },type = 12 },
[29] = {"Poliuretanowe tuleje", handling={ {"turnMass", -0.02} },type = 13 },
[30] = {"Sprężyny obniżające", handling={ {"suspensionLowerLimit", 0.1} },type = 14 },
[31] = {"Sprężyny podnoszące", handling={ {"suspensionLowerLimit", -0.1} },type = 14 },
[31] = {"Rozpórka przednia", handling={ {"turnMass", -0.05} },type = 15 },
[32] = {"Rozpórka tylnia", handling={ {"turnMass", -0.05} },type = 16 },
[33] = {"Sprzęgło ceramiczno-metalowe", handling={ {"engineAcceleration", 0.003} },type = 17 },
[34] = {"Sprzęgło kompozytowe", handling={ {"engineAcceleration", 0.005} },type = 17 },
[35] = {"Sprzęgło Węglowe", handling={ {"engineAcceleration", 0.007} },type = 17 },
[36] = {"Sprzęgło 0-1", handling={ {"engineAcceleration", 0.01} },type = 17 },
[37] = {"Skrzynia biegów z mniejszym przełożeniem", handling={ {"maxVelocity", 0.01}, {"engineAcceleration",-0.1} },type = 18 },
[38] = {"Skrzynia biegów z wiekszym przełożeniem", handling={ {"maxVelocity", -0.1}, {"engineAcceleration",0.1} },type = 18 },
[39] = {"Skrzynia biegów z wiekszym przełożeniem", handling={ {"maxVelocity", -0.1}, {"engineAcceleration",0.1} },type = 18 },
[40] = {"Otulina", handling={ {"collisionDamageMultiplier", -0.1}  },type = 19  },
[41] = {"Pół-klatka", handling={ {"turnMass", -0.07}, {"collisionDamageMultiplier", -0.2}  },type = 19  },
[42] = {"Klatka", handling={ {"turnMass", -0.12},  {"collisionDamageMultiplier", -0.3} },type = 19 },
[43] = {"OponyHigh Performence", handling={ {"tractionLoss",0.02}, {"tractionMultiplier",0.1} },type = 20 },
[44] = {"Opony Ultra-High Performence", handling={ {"tractionLoss",0.05}, {"tractionMultiplier",0.2} },type = 20 },
[45] = {"Opony Wyścigowe", handling={ {"tractionLoss",0.11}, {"tractionMultiplier",0.3} },type = 20 },
[46] = {"Opony Slick", handling={ {"tractionLoss",-0.15}, {"tractionMultiplier",-0.15} },type = 20 },
[47] = {"Pakiet I", handling={ {"mass",-0.10} },type = 21 },
[48] = {"Pakiet II", handling={ {"mass",-0.20} },type = 21 },
[49] = {"Pakiet III", handling={ {"mass",-0.30} },type = 21 },
[50] = {"Pakiet IV", handling={ {"mass",-0.40} },type = 21 },
[51] = {"Pakiet V", handling={ {"mass",-0.50} },type = 21 },
[52] = {"AWD", handling={ {"driveType", "awd"} },type = 22 },
[53] = {"RWD", handling={ {"driveType", "rwd"} },type = 22 },
[54] = {"fwd", handling={ {"driveType", "fwd"} },type = 22 }
}