local txd = engineLoadTXD("zwloki.txd")
			engineImportTXD(txd, 2060)
local dff = engineLoadDFF("zwloki.dff", 2060)
			engineReplaceModel(dff, 2060)
local col = engineLoadCOL ("zwloki.col")
			engineReplaceCOL (col, 2060)

local txd = engineLoadTXD("telefon.txd")
			engineImportTXD(txd, 330)
local dff = engineLoadDFF("telefon.dff", 330)
			engineReplaceModel(dff, 330)
local col = engineLoadCOL ("telefon.col")
			engineReplaceCOL (col, 330)

local txd = engineLoadTXD("blokada.txd")
			engineImportTXD(txd, 1282)
local dff = engineLoadDFF("blokada.dff", 1282)
			engineReplaceModel(dff, 1282)
local col = engineLoadCOL("blokada.col")
			engineReplaceCOL(col, 1282)

--local dff = engineLoadDFF("pacholek.dff", 1238)
--			engineReplaceModel(dff, 1238)
--local col = engineLoadCOL("pacholek.col")
--			engineReplaceCOL(col, 1238)

local txd = engineLoadTXD("mblokada.txd")
			engineImportTXD(txd, 1424)
local dff = engineLoadDFF("mblokada.dff", 1424)
			engineReplaceModel(dff, 1424)
local col = engineLoadCOL("mblokada.col")
			engineReplaceCOL(col, 1424)

local dff = engineLoadDFF("belka.dff", 1855)
			engineReplaceModel(dff, 1855)
local col = engineLoadCOL("belka.col")
			engineReplaceCOL(col, 1855)

local dff = engineLoadDFF("belkawylaczona.dff", 1856)
			engineReplaceModel(dff, 1856)
local col = engineLoadCOL("belka.col")
			engineReplaceCOL(col, 1856)

local txd = engineLoadTXD("halligan.txd")
			engineImportTXD(txd, 321)
local dff = engineLoadDFF("halligan.dff", 321)
			engineReplaceModel(dff, 321)
