--# Textures table

local blips_textures = {
	{ "arrow", "radar/blips/arrow.png" },
	{ "radardisc", "radar/blips/radardisc.png" },
	{ "radar_airYard", "radar/blips/radar_airYard.png" },
	{ "radar_ammugun", "radar/blips/radar_ammugun.png" },
	{ "radar_barbers", "radar/blips/radar_barbers.png" },
	{ "radar_BIGSMOKE", "radar/blips/radar_BIGSMOKE.png" },
	{ "radar_boatyard", "radar/blips/radar_boatyard.png" },
	{ "radar_bulldozer", "radar/blips/radar_bulldozer.png" },
	{ "radar_burgerShot", "radar/blips/radar_burgerShot.png" },
	{ "radar_cash", "radar/blips/radar_cash.png" },
	{ "radar_CATALINAPINK", "radar/blips/radar_CATALINAPINK.png"},
	{ "radar_centre", "radar/blips/radar_centre.png" },
	{ "radar_CESARVIAPANDO", "radar/blips/radar_CESARVIAPANDO.png" },
	{ "radar_chicken", "radar/blips/radar_chicken.png" },
	{ "radar_CJ", "radar/blips/radar_CJ.png" },
	{ "radar_CRASH1", "radar/blips/radar_CRASH1.png" },
	{ "radar_dateDisco", "radar/blips/radar_dateDisco.png" },
	{ "radar_dateDrink", "radar/blips/radar_dateDrink.png" },
	{ "radar_dateFood", "radar/blips/radar_dateFood.png" },
	{ "radar_diner", "radar/blips/radar_diner.png" },
	{ "radar_emmetGun", "radar/blips/radar_emmetGun.png" },
	{ "radar_enemyAttack", "radar/blips/radar_enemyAttack.png" },
	{ "radar_fire", "radar/blips/radar_fire.png" },
	{ "radar_Flag", "radar/blips/radar_Flag.png" },
	{ "radar_gangB", "radar/blips/radar_gangB.png" },
	{ "radar_gangG", "radar/blips/radar_gangG.png" },
	{ "radar_gangN", "radar/blips/radar_gangN.png" },
	{ "radar_gangP", "radar/blips/radar_gangP.png" },
	{ "radar_gangY", "radar/blips/radar_gangY.png" },
	{ "radar_girlfriend", "radar/blips/radar_girlfriend.png" },
	{ "radar_gym", "radar/blips/radar_gym.png" },
	{ "radar_hostpital", "radar/blips/radar_hostpital.png" },
	{ "radar_impound", "radar/blips/radar_impound.png" },
	{ "radar_light", "radar/blips/radar_light.png" },
	{ "radar_LocoSyndicate", "radar/blips/radar_LocoSyndicate.png" },
	{ "radar_MADDOG", "radar/blips/radar_MADDOG.png" },
	{ "radar_mafiaCasino", "radar/blips/radar_mafiaCasino.png" },
	{ "radar_MCSTRAP", "radar/blips/radar_MCSTRAP.png" },
	{ "radar_modGarage", "radar/blips/radar_modGarage.png" },
	{ "radar_north", "radar/blips/radar_north.png" },
	{ "radar_OGLOC", "radar/blips/radar_OGLOC.png" },
	{ "radar_pizza", "radar/blips/radar_pizza.png" },
	{ "radar_police", "radar/blips/radar_police.png" },
	{ "radar_propertyG", "radar/blips/radar_propertyG.png" },
	{ "radar_propertyR", "radar/blips/radar_propertyR.png" },
	{ "radar_qmark", "radar/blips/radar_qmark.png" },
	{ "radar_race", "radar/blips/radar_race.png" },
	{ "radar_runway", "radar/blips/radar_runway.png" },
	{ "radar_RYDER", "radar/blips/radar_RYDER.png" },
	{ "radar_saveGame", "radar/blips/radar_saveGame.png" },
	{ "radar_school", "radar/blips/radar_school.png" },
	{ "radar_spray", "radar/blips/radar_spray.png" },
	{ "radar_SWEET", "radar/blips/radar_SWEET.png" },
	{ "radar_tattoo", "radar/blips/radar_tattoo.png" },
	{ "radar_THETRUTH", "radar/blips/radar_THETRUTH.png" },
	{ "radar_TORENO", "radar/blips/radar_TORENO.png" },
	{ "radar_TorenoRanch", "radar/blips/radar_TorenoRanch.png" },
	{ "radar_triads", "radar/blips/radar_triads.png" },
	{ "radar_triadsCasino", "radar/blips/radar_triadsCasino.png" },
	{ "radar_truck", "radar/blips/radar_truck.png" },
	{ "radar_tshirt", "radar/blips/radar_tshirt.png" },
	{ "radar_waypoint", "radar/blips/radar_waypoint.png" },
	{ "radar_WOOZIE", "radar/blips/radar_WOOZIE.png" },
	{ "radar_ZERO", "radar/blips/radar_ZERO.png" },
	{ "siterocket", "radar/blips/siterocket.png" }
}

--# Apply textures

addEventHandler("onClientResourceStart", resourceRoot, 
	function()
		for i = 2, #blips_textures do
			local shader = dxCreateShader("radar/texture.fx")
				engineApplyShaderToWorldTexture(shader, blips_textures[i][1])
				dxSetShaderValue(shader, "gTexture", dxCreateTexture(blips_textures[i][2]))
		end
	end
)
--[[
local blips_textures = {
	{ "arrow", "radar/blips/arrow.png" },
	{ "radardraw", "radar/blips/radardraw.png" },
	{ "radardisc", "radar/blips/radardisc.png" },
	{ "radar_airYard", "radar/blips/radar_airYard.png" },
	{ "radar_ammugun", "radar/blips/radar_ammugun.png" },
	{ "radar_barbers", "radar/blips/radar_barbers.png" },
	{ "radar_BIGSMOKE", "radar/blips/radar_BIGSMOKE.png" },
	{ "radar_boatyard", "radar/blips/radar_boatyard.png" },
	{ "radar_bulldozer", "radar/blips/radar_bulldozer.png" },
	{ "radar_burgerShot", "radar/blips/radar_burgerShot.png" },
	{ "radar_cash", "radar/blips/radar_cash.png" },
	{ "radar_CATALINAPINK", "radar/blips/radar_CATALINAPINK.png"},
	{ "radar_centre", "radar/blips/radar_centre.png" },
	{ "radar_CESARVIAPANDO", "radar/blips/radar_CESARVIAPANDO.png" },
	{ "radar_chicken", "radar/blips/radar_chicken.png" },
	{ "radar_CJ", "radar/blips/radar_CJ.png" },
	{ "radar_CRASH1", "radar/blips/radar_CRASH1.png" },
	{ "radar_dateDisco", "radar/blips/radar_dateDisco.png" },
	{ "radar_dateDrink", "radar/blips/radar_dateDrink.png" },
	{ "radar_dateFood", "radar/blips/radar_dateFood.png" },
	{ "radar_diner", "radar/blips/radar_diner.png" },
	{ "radar_emmetGun", "radar/blips/radar_emmetGun.png" },
	{ "radar_enemyAttack", "radar/blips/radar_enemyAttack.png" },
	{ "radar_fire", "radar/blips/radar_fire.png" },
	{ "radar_Flag", "radar/blips/radar_Flag.png" },
	{ "radar_gangB", "radar/blips/radar_gangB.png" },
	{ "radar_gangG", "radar/blips/radar_gangG.png" },
	{ "radar_gangN", "radar/blips/radar_gangN.png" },
	{ "radar_gangP", "radar/blips/radar_gangP.png" },
	{ "radar_gangY", "radar/blips/radar_gangY.png" },
	{ "radar_girlfriend", "radar/blips/radar_girlfriend.png" },
	{ "radar_gym", "radar/blips/radar_gym.png" },
	{ "radar_hostpital", "radar/blips/radar_hostpital.png" },
	{ "radar_impound", "radar/blips/radar_impound.png" },
	{ "radar_light", "radar/blips/radar_light.png" },
	{ "radar_LocoSyndicate", "radar/blips/radar_LocoSyndicate.png" },
	{ "radar_MADDOG", "radar/blips/radar_MADDOG.png" },
	{ "radar_mafiaCasino", "radar/blips/radar_mafiaCasino.png" },
	{ "radar_MCSTRAP", "radar/blips/radar_MCSTRAP.png" },
	{ "radar_modGarage", "radar/blips/radar_modGarage.png" },
	{ "radar_north", "radar/blips/radar_north.png" },
	{ "radar_OGLOC", "radar/blips/radar_OGLOC.png" },
	{ "radar_pizza", "radar/blips/radar_pizza.png" },
	{ "radar_police", "radar/blips/radar_police.png" },
	{ "radar_propertyG", "radar/blips/radar_propertyG.png" },
	{ "radar_propertyR", "radar/blips/radar_propertyR.png" },
	{ "radar_qmark", "radar/blips/radar_qmark.png" },
	{ "radar_race", "radar/blips/radar_race.png" },
	{ "radar_runway", "radar/blips/radar_runway.png" },
	{ "radar_RYDER", "radar/blips/radar_RYDER.png" },
	{ "radar_saveGame", "radar/blips/radar_saveGame.png" },
	{ "radar_school", "radar/blips/radar_school.png" },
	{ "radar_spray", "radar/blips/radar_spray.png" },
	{ "radar_SWEET", "radar/blips/radar_SWEET.png" },
	{ "radar_tattoo", "radar/blips/radar_tattoo.png" },
	{ "radar_THETRUTH", "radar/blips/radar_THETRUTH.png" },
	{ "radar_TORENO", "radar/blips/radar_TORENO.png" },
	{ "radar_TorenoRanch", "radar/blips/radar_TorenoRanch.png" },
	{ "radar_triads", "radar/blips/radar_triads.png" },
	{ "radar_triadsCasino", "radar/blips/radar_triadsCasino.png" },
	{ "radar_truck", "radar/blips/radar_truck.png" },
	{ "radar_tshirt", "radar/blips/radar_tshirt.png" },
	{ "radar_waypoint", "radar/blips/radar_waypoint.png" },
	{ "radar_WOOZIE", "radar/blips/radar_WOOZIE.png" },
	{ "radar_ZERO", "radar/blips/radar_ZERO.png" },
	{ "siteM16", "radar/blips/siteM16.png" },
	{ "siterocket", "radar/blips/siterocket.png" }
}
]]